### Synthetic Bank Transaction Data Creation

In [180]:
import random
import pandas as pd
from datetime import datetime, timedelta

# Define constants
NUM_TRANSACTIONS = 300
ACCOUNT_ID = "8010-27075685-001"

MERCHANTS_NON_RECURRENT_1 = [
    "Eateries", "Hypermarket", "Groceries", "Petrol", "Entertainment"
]

MERCHANTS_NON_RECURRENT_2 = [
    "Auto Repair", "Plumber Service", "Electrician Service"
]

DEPOSIT_SOURCE_RECURRENT_EXTRA = [
    "Freelance Income", "ATM Deposit", "Check Deposit", "Wire Transfer", "Mobile Wallet Transfer", "Cash Deposit"
]
# Randomly select only 1 DEPOSIT_SOURCE_NON_RECURRENT
DEPOSIT_SOURCE_RECURRENT_EXTRA = [random.choice(DEPOSIT_SOURCE_RECURRENT_EXTRA)]

MERCHANTS_RECURRENT_ENTERTAINMENT = ["Video Streaming", "Music Streaming", "Cloud Gaming Subscription"]
# Randomly select only 2 MERCHANTS_RECURRENT_ENTERTAINMENT
MERCHANTS_RECURRENT_ENTERTAINMENT = random.sample(MERCHANTS_RECURRENT_ENTERTAINMENT, 2)

MERCHANTS_RECURRENT_FACILITIES_1 = ["Electric Company", "Insurance", "Gym Subscription"]
MERCHANTS_RECURRENT_FACILITIES_2 = ["Water Utility", "Gas Provider", "Trash Collection Service", "Cloud Service", "Public Transport Pass"]

BANK_LOAN_RECURRENT = ["House Loan", "Vehicle Loan", "Personal Loan"]
# Randomly select 1 to 3 BANK_LOAN_RECURRENT
BANK_LOAN_RECURRENT = random.sample(BANK_LOAN_RECURRENT, random.randint(1, 3))

FAMILY_CONTRIBUTION_RECURRENT_1 = ["Spouse Allowance", "Parent Allowance"]
FAMILY_CONTRIBUTION_RECURRENT_2 = ["Children Allowance"]

# Randomly select 1 to 2 FAMILY_CONTRIBUTION_RECURRENT_1
FAMILY_CONTRIBUTION_RECURRENT_1 = random.sample(FAMILY_CONTRIBUTION_RECURRENT_1, random.randint(1, 2))
# Randomly select 0 to 1 FAMILY_CONTRIBUTION_RECURRENT_2
FAMILY_CONTRIBUTION_RECURRENT_2 = random.sample(FAMILY_CONTRIBUTION_RECURRENT_2, random.randint(0, 1))

DEPOSIT_SOURCE_RECURRENT = ["Salary Deposit"]

START_DATE = datetime(2024, 1, 1)
END_DATE = datetime(2025, 2, 5)

# Generate random date between start and end dates
def random_date(start, end):
    return start + timedelta(days=random.randint(0, (end - start).days), seconds=random.randint(0, 86400))

# Generate recurrent transactions once per month
recurrent_transactions = {}

recurrent_transactions_list = [
        '"Entertainment": random.sample(MERCHANTS_RECURRENT_ENTERTAINMENT,1)',
        '"Facilities_Exp": random.sample(MERCHANTS_RECURRENT_FACILITIES_1,1)',
        '"Facilities_Chp": random.sample(MERCHANTS_RECURRENT_FACILITIES_2,1)',
        '"Loan": random.sample(BANK_LOAN_RECURRENT,1)',
        '"Family_Exp": random.sample(FAMILY_CONTRIBUTION_RECURRENT_1,1)',
        '"Family_Chp": random.sample(FAMILY_CONTRIBUTION_RECURRENT_2,1)',
        '"Deposit": random.sample(DEPOSIT_SOURCE_RECURRENT,1)',
        '"Deposit Extra": random.sample(DEPOSIT_SOURCE_RECURRENT_EXTRA,1)'
]

for data in recurrent_transactions_list:
    for month in range(1, 14):  # 13 months (Jan 2024 - Jan 2025)
        # Generate random hour (0-23) and minute (0-59)
        random_hour = random.randint(0, 23)
        random_minute = random.randint(0, 59)
        random_second = random.randint(0, 59)
        
        # Create datetime with both date and time
        month_date = datetime(
            2024 if month <= 12 else 2025,  # Year
            month if month <= 12 else 1,     # Month
            random.randint(1, 7),            # Day
            random_hour,                     # Hour
            random_minute,                   # Minute
            random_second                   # second
        )
        
        recurrent_transactions[month_date] = {
            data
        }

transactions = []

NON_RECURRENT_TRANSACTIONS = NUM_TRANSACTIONS-len(recurrent_transactions)

date_recurrents = list(recurrent_transactions.keys())

for date_loop in date_recurrents:
    if date_loop in recurrent_transactions:
        category, merchant = (recurrent_transactions[date_loop])
        # Set amount based on category
        if category == "Entertainment":
            transaction_type = "Debit"
            amount = -(round(random.uniform(100, 150), 2))
            date=date_loop
            transactions.append([ACCOUNT_ID, date, transaction_type, category, merchant, amount])
        elif category == "Facilities_Exp":
            transaction_type = "Debit"
            amount = -(round(random.uniform(200, 250), 2))
            date=date_loop
            transactions.append([ACCOUNT_ID, date, transaction_type, category, merchant, amount])
        elif category == "Facilities_Chp":
            transaction_type = "Debit"
            amount = -(round(random.uniform(50, 100), 2))
            date=date_loop
            transactions.append([ACCOUNT_ID, date, transaction_type, category, merchant, amount])
        elif category == "Loan":
            transaction_type = "Debit"
            amount = -(round(random.uniform(500, 1000), 2))
            date=date_loop
            transactions.append([ACCOUNT_ID, date, transaction_type, category, merchant, amount])
        elif category == "Family_Exp":
            transaction_type = "Debit"
            amount = -(round(random.uniform(250, 300), 2))
            date=date_loop
            transactions.append([ACCOUNT_ID, date, transaction_type, category, merchant, amount])
        elif category == "Family_Chp":
            transaction_type = "Debit"
            amount = -(round(random.uniform(50, 100), 2))
            date=date_loop
            transactions.append([ACCOUNT_ID, date, transaction_type, category, merchant, amount])
        elif category == "Deposit":
            transaction_type = "Credit"
            amount = round(random.uniform(7000, 10000), 2)
            date=date_loop
            transactions.append([ACCOUNT_ID, date, transaction_type, category, merchant, amount])
        elif category == "Deposit Extra":
            transaction_type = "Credit"
            amount = round(random.uniform(50, 150), 2)  # Keeping original range for non-recurrent
            date=date_loop
            transactions.append([ACCOUNT_ID, date, transaction_type, category, merchant, amount])
    else:
        continue

for _ in range(NON_RECURRENT_TRANSACTIONS):
    date = random_date(START_DATE, END_DATE)
    
    transaction_type = "Debit"
    category = "Non-Recurrent Expense"
    MERCHANTS_NON_RECURRENT = ['MERCHANTS_NON_RECURRENT_1','MERCHANTS_NON_RECURRENT_2']
    if random.sample(MERCHANTS_NON_RECURRENT,1) == 'MERCHANTS_NON_RECURRENT_1':
        merchant = random.sample(MERCHANTS_NON_RECURRENT_1, random.randint(0, 1))
        try:
            merchant = merchant[0]
            amount = -(round(random.uniform(50, 60), 2))  # Keeping original range for non-recurrent
        except IndexError:
            merchant = None
            amount = 0
            continue
    else:
        merchant = random.sample(MERCHANTS_NON_RECURRENT_2, random.randint(0, 1))
        try:
            merchant = merchant[0]
            amount = -(round(random.uniform(150, 250), 2))  # Keeping original range for non-recurrent
        except IndexError:
            merchant = None
            amount = 0
            continue


    transactions.append([ACCOUNT_ID, date, transaction_type, category, merchant, amount])

# Convert to DataFrame with explicit column names
df = pd.DataFrame(transactions, columns=["accountID", "date", "transactionType", "category", "merchant", "Amount"])

# Sort transactions by date
df.sort_values(by="date", inplace=True)

# Calculate cumulative balance
df["accountBAL"] = df["Amount"].cumsum().round(2)

# Save to CSV
# df.to_csv("synthetic_current_account_transactions.csv", index=False)

print("Synthetic data generated and saved as 'synthetic_current_account_transactions.csv'.")

AttributeError: 'set' object has no attribute 'items'

In [203]:
list(recurrent_transactions.keys())[0]

datetime.datetime(2024, 1, 1, 22, 39, 35)

In [211]:

recurrent_transactions[list(recurrent_transactions.keys())[0]]

{'"Entertainment": random.sample(MERCHANTS_RECURRENT_ENTERTAINMENT,1)'}

In [ ]:

recurrent_transactions[list(recurrent_transactions.keys())[0]]

{'"Entertainment": random.sample(MERCHANTS_RECURRENT_ENTERTAINMENT,1)'}

In [ ]:

recurrent_transactions[list(recurrent_transactions.keys())[0]]

{'"Entertainment": random.sample(MERCHANTS_RECURRENT_ENTERTAINMENT,1)'}

In [ ]:

recurrent_transactions[list(recurrent_transactions.keys())[0]]

{'"Entertainment": random.sample(MERCHANTS_RECURRENT_ENTERTAINMENT,1)'}

In [ ]:

recurrent_transactions[list(recurrent_transactions.keys())[0]]

{'"Entertainment": random.sample(MERCHANTS_RECURRENT_ENTERTAINMENT,1)'}

In [ ]:

recurrent_transactions[list(recurrent_transactions.keys())[0]]

{'"Entertainment": random.sample(MERCHANTS_RECURRENT_ENTERTAINMENT,1)'}

In [ ]:

recurrent_transactions[list(recurrent_transactions.keys())[0]]

{'"Entertainment": random.sample(MERCHANTS_RECURRENT_ENTERTAINMENT,1)'}

In [141]:
len(list(recurrent_transactions.keys()))

104

In [132]:
import random
import pandas as pd
from datetime import datetime, timedelta

# Define constants
NUM_TRANSACTIONS = 300
ACCOUNT_ID = "8010-27075685-001"

MERCHANTS_NON_RECURRENT_1 = [
    "Eateries", "Hypermarket", "Groceries", "Petrol", "Entertainment"
]

MERCHANTS_NON_RECURRENT_2 = [
    "Auto Repair", "Plumber Service", "Electrician Service"
]

DEPOSIT_SOURCE_RECURRENT_EXTRA = [
    "Freelance Income", "ATM Deposit", "Check Deposit", "Wire Transfer", "Mobile Wallet Transfer", "Cash Deposit"
]
# Randomly select only 1 DEPOSIT_SOURCE_NON_RECURRENT
DEPOSIT_SOURCE_RECURRENT_EXTRA = [random.choice(DEPOSIT_SOURCE_RECURRENT_EXTRA)]

MERCHANTS_RECURRENT_ENTERTAINMENT = ["Video Streaming", "Music Streaming", "Cloud Gaming Subscription"]
# Randomly select only 2 MERCHANTS_RECURRENT_ENTERTAINMENT
MERCHANTS_RECURRENT_ENTERTAINMENT = random.sample(MERCHANTS_RECURRENT_ENTERTAINMENT, 2)

MERCHANTS_RECURRENT_FACILITIES_1 = ["Electric Company", "Insurance", "Gym Subscription"]
MERCHANTS_RECURRENT_FACILITIES_2 = ["Water Utility", "Gas Provider", "Trash Collection Service", "Cloud Service", "Public Transport Pass"]

BANK_LOAN_RECURRENT = ["House Loan", "Vehicle Loan", "Personal Loan"]
# Randomly select 1 to 3 BANK_LOAN_RECURRENT
BANK_LOAN_RECURRENT = random.sample(BANK_LOAN_RECURRENT, random.randint(1, 3))

FAMILY_CONTRIBUTION_RECURRENT_1 = ["Spouse Allowance", "Parent Allowance"]
FAMILY_CONTRIBUTION_RECURRENT_2 = ["Children Allowance"]

# Randomly select 1 to 2 FAMILY_CONTRIBUTION_RECURRENT_1
FAMILY_CONTRIBUTION_RECURRENT_1 = random.sample(FAMILY_CONTRIBUTION_RECURRENT_1, random.randint(1, 2))
# Randomly select 0 to 1 FAMILY_CONTRIBUTION_RECURRENT_2
FAMILY_CONTRIBUTION_RECURRENT_2 = random.sample(FAMILY_CONTRIBUTION_RECURRENT_2, random.randint(0, 1))

DEPOSIT_SOURCE_RECURRENT = ["Salary Deposit"]

START_DATE = datetime(2024, 1, 1)
END_DATE = datetime(2025, 2, 5)

# Generate random date between start and end dates
def random_date(start, end):
    return start + timedelta(days=random.randint(0, (end - start).days), seconds=random.randint(0, 86400))

# Generate recurrent transactions once per month
recurrent_transactions = {}

recurrent_transactions_list = [
        '"Entertainment": random.sample(MERCHANTS_RECURRENT_ENTERTAINMENT,1)',
        '"Facilities_Exp": random.sample(MERCHANTS_RECURRENT_FACILITIES_1,1)',
        '"Facilities_Chp": random.sample(MERCHANTS_RECURRENT_FACILITIES_2,1)',
        '"Loan": random.sample(BANK_LOAN_RECURRENT,1)',
        '"Family_Exp": random.sample(FAMILY_CONTRIBUTION_RECURRENT_1,1)',
        '"Family_Chp": random.sample(FAMILY_CONTRIBUTION_RECURRENT_2,1)',
        '"Deposit": random.sample(DEPOSIT_SOURCE_RECURRENT,1)',
        '"Deposit Extra": random.sample(DEPOSIT_SOURCE_RECURRENT_EXTRA,1)'
]

for data in recurrent_transactions_list:
    for month in range(1, 14):  # 13 months (Jan 2024 - Jan 2025)
        # Generate random hour (0-23) and minute (0-59)
        random_hour = random.randint(0, 23)
        random_minute = random.randint(0, 59)
        random_second = random.randint(0, 59)
        
        # Create datetime with both date and time
        month_date = datetime(
            2024 if month <= 12 else 2025,  # Year
            month if month <= 12 else 1,     # Month
            random.randint(1, 7),            # Day
            random_hour,                     # Hour
            random_minute,                   # Minute
            random_second                   # second
        )
        
        recurrent_transactions[month_date] = {
            data
        }

transactions = []

NON_RECURRENT_TRANSACTIONS = NUM_TRANSACTIONS-len(recurrent_transactions)

date_recurrent = list(recurrent_transactions.keys())


for _ in range(NON_RECURRENT_TRANSACTIONS):
    date = random_date(START_DATE, END_DATE)
    
    if date in recurrent_transactions:
        category, merchant = random.choice(list(recurrent_transactions[date].items()))
        # Set amount based on category
        if category == "Entertainment":
            transaction_type = "Debit"
            amount = -(round(random.uniform(100, 150), 2))
        elif category == "Facilities_Exp":
            transaction_type = "Debit"
            amount = -(round(random.uniform(200, 250), 2))
        elif category == "Facilities_Chp":
            transaction_type = "Debit"
            amount = -(round(random.uniform(50, 100), 2))
        elif category == "Loan":
            transaction_type = "Debit"
            amount = -(round(random.uniform(500, 1000), 2))
        elif category == "Family_Exp":
            transaction_type = "Debit"
            amount = -(round(random.uniform(250, 300), 2))
        elif category == "Family_Chp":
            transaction_type = "Debit"
            amount = -(round(random.uniform(50, 100), 2))
        elif category == "Deposit":
            transaction_type = "Credit"
            amount = round(random.uniform(7000, 10000), 2)
        elif category == "Deposit Extra":
            transaction_type = "Credit"
            amount = round(random.uniform(50, 150), 2)  # Keeping original range for non-recurrent
    else:
        if transaction_type == "Debit":
            category = "Non-Recurrent Expense"
            MERCHANTS_NON_RECURRENT = ['MERCHANTS_NON_RECURRENT_1','MERCHANTS_NON_RECURRENT_2']
            if random.sample(MERCHANTS_NON_RECURRENT,1) == 'MERCHANTS_NON_RECURRENT_1':
                merchant = random.sample(MERCHANTS_NON_RECURRENT_1, random.randint(0, 1))
                try:
                    merchant = merchant[0]
                    amount = -(round(random.uniform(50, 60), 2))  # Keeping original range for non-recurrent
                except IndexError:
                    merchant = None
                    amount = 0
                    continue
            else:
                merchant = random.sample(MERCHANTS_NON_RECURRENT_2, random.randint(0, 1))
                try:
                    merchant = merchant[0]
                    amount = -(round(random.uniform(150, 250), 2))  # Keeping original range for non-recurrent
                except IndexError:
                    merchant = None
                    amount = 0
                    continue
        else:
            continue

    transactions.append([ACCOUNT_ID, date, transaction_type, category, merchant, amount])

# Convert to DataFrame with explicit column names
df = pd.DataFrame(transactions, columns=["accountID", "date", "transactionType", "category", "merchant", "Amount"])

# Sort transactions by date
df.sort_values(by="date", inplace=True)

# Calculate cumulative balance
df["accountBAL"] = df["Amount"].cumsum().round(2)

# Save to CSV
# df.to_csv("synthetic_current_account_transactions.csv", index=False)

print("Synthetic data generated and saved as 'synthetic_current_account_transactions.csv'.")

,accountID,date,transactionType,merchant,Amount,accountBAL
category,,,,,,
Non-Recurrent Expense,80,80,80,80,80,80

In [133]:
df

,accountID,date,transactionType,category,merchant,Amount,accountBAL
37,8010-27075685-001,2024-01-01 13:46:38,Debit,Non-Recurrent Expense,Plumber Service,-226.82,-226.82
45,8010-27075685-001,2024-01-02 22:13:23,Debit,Non-Recurrent Expense,Auto Repair,-190.13,-416.95
29,8010-27075685-001,2024-01-08 07:14:32,Debit,Non-Recurrent Expense,Auto Repair,-167.28,-584.23
25,8010-27075685-001,2024-01-17 08:32:27,Debit,Non-Recurrent Expense,Plumber Service,-190.30,-774.53
28,8010-27075685-001,2024-01-19 11:28:34,Debit,Non-Recurrent Expense,Plumber Service,-170.73,-945.26
...,...,...,...,...,...,...,...
18,8010-27075685-001,2025-01-25 14:53:16,Debit,Non-Recurrent Expense,Auto Repair,-217.69,-15031.38
77,8010-27075685-001,2025-01-29 13:42:31,Debit,Non-Recurrent Expense,Electrician Service,-208.76,-15240.14
63,8010-27075685-001,2025-01-31 09:29:06,Debit,Non-Recurrent Expense,Plumber Service,-199.88,-15440.02
5,8010-27075685-001,2025-02-01 11:05:21,Debit,Non-Recurrent Expense,Electrician Service,-231.73,-15671.75
62,8010-27075685-001,2025-02-03 06:04:47,Debit,Non-Recurrent Expense,Electrician Service,-228.94,-15900.69

### Create Account ID

In [ ]:
# direct query

'''
UPDATE cif
SET accountID = 
    CASE 
        -- Savings Account: Format 8010-IC-001 (starts with 8010)
        WHEN productID = 1 THEN 
            '8010-' || substr('00000000' || ic, -8) || '-' ||
            substr('000' || id, -3)
        
        -- Current Account: Format 8020-IC-001 (starts with 8020)
        WHEN productID = 2 THEN 
            '8020-' || substr('00000000' || ic, -8) || '-' ||
            substr('000' || id, -3)
    END
WHERE productID IN (1, 2)

'''


# connect to sqlite
import sqlite3
conn = sqlite3.connect('instance/flaskr.sqlite')
print("Opened database successfully")

# pandas read from sqlite
import pandas as pd
#pd.read_sql_query("select * from 'productID(1)-transactions'", conn)

# write pandas df to sqlite table
#df = pd.read_csv('synthetic_current_account_transactions.csv')
#df.to_sql('productID(1)-transactions', conn, if_exists='append', index=False)

df=pd.read_sql_query("select * from 'productID(1)-transactions'", conn)
df['accountBAL']=(df['transactionAMT'].cumsum()).round(2)
df

#conn.close()

Opened database successfully

,accountID,transactionDATE,transactionTYPE,description,amount,accountBAL
0,8010-27075685-001,2024-01-01 05:11:51,Merchant Payment,Payment to Hermo,-178.52,-178.52
1,8010-27075685-001,2024-01-01 08:40:42,Salary Deposit,Salary Deposit,9929.20,9750.68
2,8010-27075685-001,2024-01-01 10:21:04,Deposit,Payment for Electronics Sale Proceeds,772.86,10523.54
3,8010-27075685-001,2024-01-01 14:11:09,Withdrawal,ATM Withdrawal,-98.67,10424.87
4,8010-27075685-001,2024-01-01 18:16:54,Bank Fee,Overdraft Fee,-30.79,10394.08
...,...,...,...,...,...,...
995,8010-27075685-001,2025-02-03 19:50:47,Withdrawal,ATM Withdrawal,-1996.43,1623481.60
996,8010-27075685-001,2025-02-03 22:59:57,Bank Fee,Transfer Fee,-25.11,1623456.49
997,8010-27075685-001,2025-02-04 07:31:04,Bill Payment,Payment to Sewage Service,-709.64,1622746.85
998,8010-27075685-001,2025-02-04 14:49:35,Salary Deposit,Salary Deposit,9647.90,1632394.75
999,8010-27075685-001,2025-02-05 15:51:37,Withdrawal,ATM Withdrawal,-873.50,1631521.25